## Assignment: Write Hello World

Write a program that uses a print statement to say 'hello world' as shown in 'Desired Output'.

In [1]:
print ("hello world")

hello world


## Assignment 2.2

2.2 Write a program that uses input to prompt a user for their name and then welcomes them. Note that input will pop up a dialog box. Enter Sarah in the pop-up box when you are prompted so your output will match the desired output.

In [2]:
name = input("Enter your name")
print("Hello " + name)

Enter your name1
Hello 1


## Assignment 2.3

2.3 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Use 35 hours and a rate of 2.75 per hour to test the program (the pay should be 96.25). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking or bad user data.

In [3]:
# This first line is provided for you

hrs = input("Enter Hours:")
rate = input("Enter Rate:")
print ("Pay:", float(rate) *  float(hrs))

Enter Hours:35
Enter Rate:2.75
Pay: 96.25


## Assignment 3.1

3.1 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay the hourly rate for the hours up to 40 and 1.5 times the hourly rate for all hours worked above 40 hours. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input - assume the user types numbers properly.

In [4]:
hrs = input("Enter Hours:")
rate = input("Enter Rate:")
h = float(hrs)
r = float(rate)
if h > 40:
    print ((h - 40) * r * 1.5 + 40 * r)
else:
    print (h * r)

Enter Hours:45
Enter Rate:10.5
498.75


## Assignment 3.3

In [5]:
try:
    score = input("Enter Score: ")
    score = float(score)
except:
    print("score input error")
    quit()
    
if score < 0 or score > 1:
    print("input error")
elif 1 > score >=0.9 :
    print ("A")
elif 0.9 > score >= 0.8 :
    print ("B")
elif 0.8 > score >= 0.7 :
    print ("C")
elif 0.7 >socre >=0.6 :
    print ("D")
else :
    print("F")
    

Enter Score: 0.85
B


## Assignment 4.6

4.6 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of time-and-a-half in a function called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. Do not name your variable sum or use the sum() function.

In [7]:
def computepay(h,r):
    if h > 40:
        return (h - 40) * r * 1.5 + 40 * r
    else :
        return h * r

hrs = input("Enter Hours:")
h = float(hrs)
rate = input("Enter Rate:")
r = float(rate)
p = computepay(h, r)
print(p)

Enter Hours:45
Enter Rate:10.5
498.75


## Assignment 5.2

5.2 Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. Enter 7, 2, bob, 10, and 4 and match the output below.

In [8]:
largest = -1
smallest = 0x3f3f3f3f
while True:
    num = input("Enter a number: ")
    if num == "done" : break
    try:
        num = int(num)
    except:
        print("Invalid input")
        continue
    if num > largest:
        largest = num
    if num < smallest:
        smallest = num

print("Maximum is", largest)
print("Minimum is", smallest)

Enter a number: 7
Enter a number: 2
Enter a number: bob
Invalid input
Enter a number: 10
Enter a number: 4
Enter a number: done
Maximum is 10
Minimum is 2


## Assignment 6.5

6.5 Write code using find() and string slicing (see section 6.10) to extract the number at the end of the line below. Convert the extracted value to a floating point number and print it out.

In [9]:
text = "X-DSPAM-Confidence:    0.8475";

spacePos = text.find(" ")
number = text[spacePos::1]
strippedNumber = number.lstrip();
result = float(strippedNumber)

def reprint(printed):
    print (printed)
    
reprint(result)

0.8475
